### ISSUE TITLE
[Bug] `actions_post_reactions_total` field always null

### ISSUE THREAD

**Issue by zhyatt** [fivetran/dbt_facebook_pages#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The `actions_post_reactions_total` field is always null, regardless of how many actions of the various types exist (anger, haha, like, etc.)

### Expected behavior

The `actions_post_reactions_total` field should be a sum of the total actions of every type. Given this is more of an aggregation of some data, perhaps this doesn't belong in this package after all and should be removed altogether. Although it could be an upstream issue, see Additional Context below for more detail.

### dbt Project configurations

Just the standard ones to get the `facebook_pages_source` package working

### Package versions

v0.2.0

### What database are you using dbt with?

bigquery

### dbt Version

dbt v1.3.1

### Additional Context

When using the Fivetran Facebook Pages connector to ingest the data, the `daily_page_metrics_total` source table doesn't appear to have the column `page_actions_post_reactions_total` (which is what this package is ultimately trying to read it seems) but instead only has the individual type totals:

`page_actions_post_reactions_anger_total`
`page_actions_post_reactions_haha_total`
`page_actions_post_reactions_like_total`
`page_actions_post_reactions_love_total`
`page_actions_post_reactions_sorry_total`

There is a chance the package isn't wrong in assuming this field should be there and instead the issue is with the upstream connector not populating a field that it should be.

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @zhyatt thanks for opening this issue and no worries that it is in this repo.

I did some quick digging and wanted to highlight that we don't actually perform any transformations on this field. In fact, in the staging model we are only renaming it. See [here](https://github.com/fivetran/dbt_facebook_pages_source/blob/e908d6075c297dcf94e59aafe554b25486b558e1/models/stg_facebook_pages__daily_page_metrics_total.sql#L38) for the snippet where we renamed the field. Likewise, in the end model, we only reference that field from the staging model (seen [here](https://github.com/fivetran/dbt_facebook_pages/blob/1da022f9c711b07f6d830bd0d828456aaabb6fc4/models/facebook_pages__pages_report.sql#L17)).

You do make a great observation though that the individual reaction type totals being populated seems accurate and is strange that the total field is not. This may be something we can address within the package. However, I would first want to understand why the total field is not being populated in the source data. For the time being, I would recommend opening a [support ticket](https://support.fivetran.com/hc/en-us) for our support and engineering teams to investigate the data being synced by the connector. 

Additionally, I noticed you mentioned you would be open to creating a PR to address this issue. My thought would be to perform something similar to the following in the [staging model](https://github.com/fivetran/dbt_facebook_pages_source/blob/e908d6075c297dcf94e59aafe554b25486b558e1/models/stg_facebook_pages__daily_page_metrics_total.sql#L33-L38):

```sql
        page_actions_post_reactions_anger_total as actions_post_reactions_anger_total,
        page_actions_post_reactions_haha_total as actions_post_reactions_haha_total,
        page_actions_post_reactions_like_total as actions_post_reactions_like_total,
        page_actions_post_reactions_love_total as actions_post_reactions_love_total,
        page_actions_post_reactions_sorry_total as actions_post_reactions_sorry_total,
        coalesce(page_actions_post_reactions_total,(page_actions_post_reactions_anger_total + page_actions_post_reactions_haha_total + page_actions_post_reactions_like_total + page_actions_post_reactions_love_total + page_actions_post_reactions_sorry_total)) as actions_post_reactions_total,
```

This would ensure we are totally the reactions manually if the total from the source is showing as `null`. We could pursue this in a PR for the package in the interim. However, I would still encourage you to open a support ticket as this is something I don't believe should not be showing as `null` in the source data. Let me know if you have any questions!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @zhyatt I just got confirmation that the `actions_post_reactions_total` was in fact removed from the connector. As such, we will want to move forward with applying the updates proposed to the dbt package.

I see you are interested in opening a PR. If you are still in fact open to contributing, I would be happy to review your PR with these proposed changes. Otherwise, my team can work on this update in our upcoming sprint. Let me know!

**Comment by fivetran-joemarkiewicz** [comment]
@zhyatt thank you again for your help in addressing this issue! The latest release will include your changes and the original issue identified here should be addressed.

As such, I will close this issue.
